spring:
  application:
    name: springBatchSample
  profiles:
    active: local
    group:
      local: storeDs, backupDs
  batch:
    jdbc:
      initialize-schema: never

batch:
  domain:
    datasource:
      poolName: batch-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3306/batch?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul"
      username: root
      password: root
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 60000
      maxLifetime: 60000
      maximumPoolSize: 5

logging:
  level:
    com.example.spring.batch: DEBUG
