mybatis:
  type-aliases-package: com.example.spring.base.dto.**, com.example.spring.base.entity.**
  mapper-locations: backup-mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

backup:
  domain:
    datasource:
      poolName: backup-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3306/backup?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul"
      username: root
      password: root
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 60000
      maxLifetime: 60000
      maximumPoolSize: 5

logging:
  level:
    com.example.spring.backup: DEBUG